### ISSUE TITLE
Add some content to github-test-demo > ReadMe.md file.

### ISSUE THREAD

**Issue by rajlearner17** [Debu-Github/github-test-demo#2]
Hi Debu
Make a change to the repo read me file and send me review request for some exchanges on the review process.

- copy paste below section in read me, we write all document directly in the product code base in MARKDOWN, explore https://www.markdowntutorial.com/ and make sure you understand below section. Lab hours to learn markdown is 2 hrs if you get hands on to experiment. 

TASK

- Just get your repo into VS code
- Make sure you are in master branch
- create new branch (got checkout -b <name your branch> 
- Make sure you follow the right standard of the branch name justifying the work in short and crisp, I wud do like readme-update
- Read this https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices

--- CONTENT TO UPDATE ---

# Overview

This guide provides information on how to work with Github at Turbot.

## Issues

Issues should be created to be as specific as possible, allowing for a clear history of changes and the reason for doing them. Another benefit to small, specific changes, is to make code review or backing out a change as easy as possible.

### Policies

Issues for policies should have a title that matches the format `Action Provider > Service > Resource > Policy Type Policies`. For example, `Add AWS > IAM > User > Approved Policies`.

## Labels

All labels should start with `# ` and the label name should be Camel case (lower).

**Comment by debabrat-git** [comment]
I have made changes as per the above comment along with how to include inner links, bullet list, inner images, block quotes etc . Please review and let me know what other items to work on. Thank you

**Comment by rajlearner17** [comment]
Well, there is a mistake. Your merge should have closed this issue which is not, I told you to merge with this commit, 

Add some content to github-test-demo > ReadMe.md file. enhancement. Closes #2

Anyway next time as long as you understand the scope of commit, lets move out of this and focus on CLIs
